name: TEST_CI

on:
  pull_request:
    types: [opened]
    branches:
      - '**'
      - '!main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Backend PR opened
        id: slack-be-pr-opened
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C07DN3TETSL'
          payload: |
            {
              "text": "Backend PR opened: ${{ github.event.pull_request.html_url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<@U07D1PWSLSG> Backend PR opened: <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
